/*
  # Seed Initial Timeline Data

  1. Insert Topics
    - Seven Wonders of the World
    - World War II Timeline
    - Ancient Civilizations
    - Ancient History of Rwanda
    - Details of Rwandan Kingdoms
    - Independence Movements
    - Scientific Milestones
    - Cultural Revolutions and Movements
    - Global Conflicts
    - Influential Figures

  2. Insert Events
    - All events from the existing timeline data
    - Properly linked to their topics
    - Related topic references maintained
*/

-- Insert topics
INSERT INTO public.topics (id, name, default_display_mode) VALUES
  ('seven-wonders', 'Seven Wonders of the World', 'years'),
  ('wwii', 'World War II Timeline', 'years'),
  ('ancient-civilizations', 'Ancient Civilizations', 'years'),
  ('ancient-rwanda', 'Ancient History of Rwanda', 'years'),
  ('rwandan-kingdoms', 'Details of Rwandan Kingdoms', 'years'),
  ('independence-movements', 'Independence Movements', 'years'),
  ('scientific-milestones', 'Scientific Milestones', 'years'),
  ('cultural-revolutions', 'Cultural Revolutions and Movements', 'years'),
  ('global-conflicts', 'Global Conflicts', 'years'),
  ('influential-figures', 'Influential Figures', 'years')
ON CONFLICT (id) DO NOTHING;

-- Insert Seven Wonders events
INSERT INTO public.events (id, topic_id, title, date, year, description, short_description, image_url, details_url, tags) VALUES
  ('great-pyramid', 'seven-wonders', 'Great Pyramid of Giza', '2580–2560 BCE', -2570, 'Constructed around 2560 BCE, the Great Pyramid of Giza is the oldest and largest of the three pyramids at Giza. Built as the tomb of Pharaoh Khufu, it originally stood 146.6 meters tall and remained the tallest man-made structure for millennia. It is the only one of the Seven Wonders of the Ancient World still largely intact.', 'The Great Pyramid of Giza, built as Pharaoh Khufu''s tomb, is the oldest and largest of the ancient world''s wonders.', 'https://images.pexels.com/photos/262780/pexels-photo-262780.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Great_Pyramid_of_Giza', ARRAY['Ancient Egypt', 'Pyramids', 'Architecture', 'Old Kingdom']),
  ('hanging-gardens', 'seven-wonders', 'Hanging Gardens of Babylon', 'c. 600 BCE', -600, 'Described by ancient writers as an ascending series of tiered gardens with a wide variety of trees, shrubs, and vines, the Hanging Gardens were considered an engineering marvel of the ancient world.', 'Legendary tiered gardens with diverse vegetation, resembling a large green mountain.', 'https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Hanging_Gardens_of_Babylon', ARRAY['Babylon', 'Gardens', 'Engineering']),
  ('statue-zeus', 'seven-wonders', 'Statue of Zeus at Olympia', '435 BCE', -435, 'Crafted by the sculptor Phidias around 435 BCE, this seated statue of Zeus was approximately 12 meters tall and regarded as one of the greatest sculptures of the ancient world.', 'A giant 12‑meter tall seated statue of Zeus, crafted by Phidias.', 'https://images.pexels.com/photos/16437843/pexels-photo-16437843/free-photo-of-ancient-greek-statue.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Statue_of_Zeus_at_Olympia', ARRAY['Ancient Greece', 'Sculpture', 'Zeus']),
  ('temple-artemis', 'seven-wonders', 'Temple of Artemis at Ephesus', 'c. 550 BCE', -550, 'Dedicated to the goddess Artemis, this temple was rebuilt twice due to fire and flood, and in its final form stood as one of the most ornate structures of the ancient world.', 'A magnificent Greek temple dedicated to Artemis, rebuilt twice after destruction.', 'https://images.pexels.com/photos/8134595/pexels-photo-8134595.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Temple_of_Artemis', ARRAY['Ancient Greece', 'Temple', 'Artemis']),
  ('mausoleum-halicarnassus', 'seven-wonders', 'Mausoleum at Halicarnassus', '353–350 BCE', -353, 'Erected for Mausolus, a Persian satrap, and his sister-wife Artemisia II, this ornate tomb stood approximately 45 meters high and combined Greek, Egyptian, and Lycian design elements.', 'A 45‑meter tall tomb built for Mausolus and his sister-wife Artemisia II.', 'https://images.pexels.com/photos/12935073/pexels-photo-12935073.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Mausoleum_at_Halicarnassus', ARRAY['Persian Empire', 'Tomb', 'Architecture']),
  ('colossus-rhodes', 'seven-wonders', 'Colossus of Rhodes', '280 BCE', -280, 'This bronze statue of Helios stood over 30 meters high at the harbor entrance in Rhodes, commemorating the island''s defense against Cyprus and becoming one of the tallest statues of its time.', 'A towering 33‑meter statue of Helios built to celebrate victory over Cyprus.', 'https://images.pexels.com/photos/8728382/pexels-photo-8728382.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Colossus_of_Rhodes', ARRAY['Ancient Greece', 'Statue', 'Helios']),
  ('lighthouse-alexandria', 'seven-wonders', 'Lighthouse of Alexandria', 'c. 280–247 BCE', -280, 'Built by the Ptolemaic Kingdom, this lighthouse stood between 120 and 137 meters tall, making it one of the tallest man-made structures of the ancient world and a vital navigational aid.', 'A massive lighthouse (120–137 m tall) guiding ships into Alexandria harbor.', 'https://images.pexels.com/photos/1840624/pexels-photo-1840624.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Lighthouse_of_Alexandria', ARRAY['Ancient Egypt', 'Lighthouse', 'Navigation'])
ON CONFLICT (id) DO NOTHING;

-- Insert WWII events
INSERT INTO public.events (id, topic_id, title, date, year, description, short_description, image_url, details_url, tags) VALUES
  ('invasion-poland', 'wwii', 'Invasion of Poland', 'September 1, 1939', 1939, 'Germany invaded Poland on 1 September 1939, prompting Britain and France to declare war two days later, officially beginning World War II in Europe.', 'Germany invades Poland, marking the start of WWII.', 'https://images.pexels.com/photos/63324/pexels-photo-63324.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Invasion_of_Poland', ARRAY['Germany', 'Poland', 'Invasion']),
  ('battle-britain', 'wwii', 'Battle of Britain', 'July–October 1940', 1940, 'From 10 July to 31 October 1940, the RAF defended the UK against the Luftwaffe in the first major military campaign fought entirely by air.', 'The first major campaign fought entirely by air forces.', 'https://images.pexels.com/photos/62622/pexels-photo-62622.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Battle_of_Britain', ARRAY['Britain', 'Air Force', 'Defense']),
  ('operation-barbarossa', 'wwii', 'Operation Barbarossa', 'June 22, 1941', 1941, 'On 22 June 1941, Nazi Germany initiated the largest military operation in history by invading the Soviet Union, ultimately involving over 3.8 million troops.', 'Nazi Germany launches its invasion of the Soviet Union.', 'https://images.pexels.com/photos/12461486/pexels-photo-12461486.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Operation_Barbarossa', ARRAY['Germany', 'Soviet Union', 'Invasion']),
  ('pearl-harbor', 'wwii', 'Attack on Pearl Harbor', 'December 7, 1941', 1941, 'On 7 December 1941, the Imperial Japanese Navy Air Service carried out a surprise strike on Pearl Harbor, prompting the United States to enter WWII.', 'Japanese carriers launch a surprise attack on the US Pacific Fleet.', 'https://images.pexels.com/photos/12935206/pexels-photo-12935206.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Attack_on_Pearl_Harbor', ARRAY['Japan', 'United States', 'Naval Attack']),
  ('d-day', 'wwii', 'D-Day Normandy Landings', 'June 6, 1944', 1944, 'On 6 June 1944, Allied forces launched Operation Overlord, the largest seaborne invasion in history, marking the liberation of German-occupied Western Europe.', 'Allied forces launch the largest amphibious invasion to liberate Western Europe.', 'https://images.pexels.com/photos/12935195/pexels-photo-12935195.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Normandy_landings', ARRAY['Allies', 'Normandy', 'Liberation']),
  ('victory-europe', 'wwii', 'Victory in Europe Day', 'May 8, 1945', 1945, 'Victory in Europe Day marks the 8 May 1945 surrender of Nazi Germany to the Allies, ending WWII in Europe.', 'Germany surrenders unconditionally, ending WWII in Europe.', 'https://images.pexels.com/photos/12935211/pexels-photo-12935211.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Victory_in_Europe_Day', ARRAY['Victory', 'Europe', 'Surrender'])
ON CONFLICT (id) DO NOTHING;

-- Insert Ancient Civilizations events
INSERT INTO public.events (id, topic_id, title, date, year, description, short_description, image_url, details_url, tags) VALUES
  ('mesopotamia', 'ancient-civilizations', 'Rise of Mesopotamia', 'c. 3500 BCE', -3500, 'Around 3500 BCE in modern Iraq, the Sumerians built Uruk with its ziggurats and developed cuneiform writing, establishing one of humanity''s first civilizations.', 'The "Cradle of Civilization" where the first cities and writing systems emerged.', 'https://images.pexels.com/photos/12935073/pexels-photo-12935073.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Mesopotamia', ARRAY['Mesopotamia', 'Sumerians', 'Civilization']),
  ('ancient-egypt', 'ancient-civilizations', 'Ancient Egyptian Civilization', 'c. 3100 BCE', -3100, 'In c. 3100 BCE, King Narmer unified Upper and Lower Egypt, beginning dynastic rule that built pyramids, developed hieroglyphs, and established complex religious practices lasting millennia.', 'Unification of Egypt launches one of history''s longest empires under the pharaohs.', 'https://images.pexels.com/photos/262780/pexels-photo-262780.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Ancient_Egypt', ARRAY['Egypt', 'Pharaohs', 'Pyramids']),
  ('indus-valley', 'ancient-civilizations', 'Indus Valley Civilization', 'c. 2600 BCE', -2600, 'Flourishing from c. 2600–1900 BCE in present‑day Pakistan and northwest India, cities like Mohenjo‑daro featured grid layouts, advanced drainage, and standardized weights, reflecting remarkable urban planning.', 'A Bronze Age civilization in South Asia known for planned cities and drainage.', 'https://images.pexels.com/photos/12935195/pexels-photo-12935195.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Indus_Valley_Civilisation', ARRAY['Indus Valley', 'Urban Planning', 'Bronze Age']),
  ('ancient-china', 'ancient-civilizations', 'Ancient Chinese Civilization', 'c. 2070 BCE', -2070, 'The Xia Dynasty (c. 2070–1600 BCE) is traditionally China''s first dynasty. Subsequent dynasties introduced the compass, gunpowder, paper, and printing, profoundly influencing global history.', 'The Xia Dynasty marks the beginning of dynastic rule; later innovations include paper and gunpowder.', 'https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/History_of_China', ARRAY['China', 'Xia Dynasty', 'Innovation']),
  ('ancient-greece', 'ancient-civilizations', 'Ancient Greek Civilization', 'c. 800 BCE', -800, 'Starting around 800 BCE, Greek city‑states laid foundations for democracy (Athens), philosophy (Plato, Aristotle), theater, and the Olympic Games, shaping Western civilization.', 'The Archaic period begins; Greeks develop democracy, philosophy, theater, and the Olympics.', 'https://images.pexels.com/photos/16437843/pexels-photo-16437843/free-photo-of-ancient-greek-statue.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Ancient_Greece', ARRAY['Greece', 'Democracy', 'Philosophy']),
  ('roman-empire', 'ancient-civilizations', 'Roman Empire', '27 BCE', -27, 'In 27 BCE, Octavian (Augustus) became the first Roman Emperor, ending the Republic and initiating centuries of Roman rule that spread law, architecture, and Latin across Europe.', 'Augustus becomes first emperor, transforming the Republic into an empire.', 'https://images.pexels.com/photos/8134595/pexels-photo-8134595.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Roman_Empire', ARRAY['Rome', 'Empire', 'Augustus'])
ON CONFLICT (id) DO NOTHING;

-- Insert Ancient Rwanda events with related topic references
INSERT INTO public.events (id, topic_id, title, date, year, description, short_description, image_url, details_url, tags, related_topic_id) VALUES
  ('early-settlement', 'ancient-rwanda', 'Early Human Settlement', '10,000 BCE', -10000, 'The earliest inhabitants were hunter-gatherer communities (ancestors of the Twa pygmies) who settled in forested regions of present-day Rwanda, developing deep knowledge of the local environment.', 'Hunter-gatherer groups, ancestors of the Twa, establish the earliest known settlements.', 'https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/History_of_Rwanda', ARRAY['Twa', 'Hunter-Gatherers', 'Settlement'], NULL),
  ('bantu-migration', 'ancient-rwanda', 'Bantu Migrations and Iron Age', 'c. 1000 BCE', -1000, 'Around 1000 BCE, Bantu-speaking peoples entered the Great Lakes region, bringing iron-smelting technology and settled agriculture, reshaping local economies and societies.', 'Bantu-speaking farmers migrate in, introducing iron-working and agriculture.', 'https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Bantu_expansion', ARRAY['Bantu Migration', 'Iron Age', 'Agriculture'], NULL),
  ('clan-societies', 'ancient-rwanda', 'Formation of Clans and Chieftaincies', 'c. 500 CE', 500, 'By 500 CE, Rwandan society organized into clans led by chieftains who governed local affairs, setting the stage for later centralized kingdoms.', 'Clan-based chieftaincies emerge as early political structures.', 'https://images.pexels.com/photos/12935073/pexels-photo-12935073.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/History_of_Rwanda', ARRAY['Clans', 'Chieftaincies', 'Social Structure'], NULL),
  ('first-kingdoms', 'ancient-rwanda', 'Emergence of Small Kingdoms', 'c. 1000 CE', 1000, 'By the 11th century, multiple small kingdoms had formed, with distinct dynasties and cultural practices, often competing or allying with neighbors.', 'Several small kingdoms form, each with its own customs and rulers.', 'https://images.pexels.com/photos/8134595/pexels-photo-8134595.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/History_of_Rwanda', ARRAY['Kingdoms', 'Political Development', 'Great Lakes'], 'rwandan-kingdoms'),
  ('gihanga-legend', 'ancient-rwanda', 'Legendary Founder Gihanga', 'c. 1400 CE', 1400, 'Rwandan oral histories recount Gihanga as the first king, introducing cattle herding, fire, and metalworking, thus shaping early cultural and political structures.', 'Gihanga, in oral tradition, is credited with founding the Rwandan kingdom.', 'https://images.pexels.com/photos/1840624/pexels-photo-1840624.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Gihanga', ARRAY['Gihanga', 'Oral Tradition', 'Kingdom'], 'rwandan-kingdoms'),
  ('nyiginya-dynasty', 'ancient-rwanda', 'Rise of the Nyiginya Dynasty', 'c. 1500 CE', 1500, 'Between the 15th and 16th centuries, the Tutsi Nyiginya clan unified territory and established the institutions of the Rwandan kingdom that would endure for centuries.', 'The Nyiginya (Tutsi) dynasty consolidates power in central Rwanda.', 'https://images.pexels.com/photos/16437843/pexels-photo-16437843/free-photo-of-ancient-greek-statue.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Kingdom_of_Rwanda', ARRAY['Nyiginya Dynasty', 'Tutsi Monarchy', 'Centralization'], 'rwandan-kingdoms'),
  ('ruganzu-ndori', 'ancient-rwanda', 'Reign of Ruganzu Ndori', 'c. 1510 CE', 1510, 'Ruganzu the Great led military campaigns that extended Rwandan borders and built the royal institutions that underpinned the kingdom''s power for generations.', 'King Ruganzu II Ndoli expands territory and strengthens institutions.', 'https://images.pexels.com/photos/8728382/pexels-photo-8728382.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Ruganzu_II_Ndoli', ARRAY['Ruganzu II Ndoli', 'Expansion', 'Institution Building'], 'rwandan-kingdoms'),
  ('ubuhake-system', 'ancient-rwanda', 'Establishment of Ubuhake', 'c. 1600 CE', 1600, 'By the 17th century, ubuhake (cattle-client) relationships structured Rwandan society, with cattle-owners granting livestock to clients in exchange for service and loyalty.', 'The cattle-based patronage system underpins social hierarchy.', 'https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Ubuhake', ARRAY['Ubuhake', 'Social System', 'Cattle Patronage'], 'rwandan-kingdoms'),
  ('mazimpaka', 'ancient-rwanda', 'Reign of Mazimpaka', '1746 CE', 1746, 'King Mazimpaka''s mid-18th-century reign saw significant territorial expansion and sophistication of royal ceremonies, marking the apex of precolonial Rwandan monarchy.', 'King Mazimpaka expands territory and refines court rituals.', 'https://images.pexels.com/photos/12935073/pexels-photo-12935073.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Mazimpaka', ARRAY['Mazimpaka', 'Expansion', 'Court Rituals'], 'rwandan-kingdoms'),
  ('rwabugiri-reign', 'ancient-rwanda', 'Reign of Kigeli IV Rwabugiri', '1853–1895 CE', 1853, 'Rwabugiri led military campaigns that brought Rwanda to its largest size and oversaw initial contact with European explorers, maintaining independence through diplomacy and force.', 'Rwabugiri expands Rwanda to its greatest extent and engages with Europeans.', 'https://images.pexels.com/photos/8134595/pexels-photo-8134595.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Kigeli_IV_Rwabugiri', ARRAY['Rwabugiri', 'Expansion', 'Explorers'], 'rwandan-kingdoms')
ON CONFLICT (id) DO NOTHING;

-- Insert Rwandan Kingdoms events
INSERT INTO public.events (id, topic_id, title, date, year, description, short_description, image_url, details_url, tags) VALUES
  ('gihanga-founding', 'rwandan-kingdoms', 'Gihanga Founds the Kingdom', 'c. 1091 CE', 1091, 'According to oral tradition, Gihanga was the first king of Rwanda who came from the heavens and established the kingdom. He is credited with introducing cattle, fire, and iron-working to the people of Rwanda.', 'Legendary king Gihanga establishes the first Rwandan kingdom.', 'https://images.pexels.com/photos/1840624/pexels-photo-1840624.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Gihanga', ARRAY['Gihanga', 'Foundation', 'Oral Tradition']),
  ('kigwa-dynasty', 'rwandan-kingdoms', 'Kigwa and the Divine Lineage', 'c. 1120 CE', 1120, 'Kigwa, believed to be the son of Gihanga, continued the royal lineage and established many of the royal customs and ceremonies that would define Rwandan kingship for centuries.', 'Kigwa, son of Gihanga, establishes the divine royal lineage.', 'https://images.pexels.com/photos/16437843/pexels-photo-16437843/free-photo-of-ancient-greek-statue.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Kingdom_of_Rwanda', ARRAY['Kigwa', 'Royal Lineage', 'Divine Kingship']),
  ('nyiginya-consolidation', 'rwandan-kingdoms', 'Nyiginya Clan Consolidation', 'c. 1400 CE', 1400, 'The Nyiginya clan, claiming descent from Gihanga, consolidated power in central Rwanda and established the administrative and military institutions that would govern the kingdom for centuries.', 'The Nyiginya clan consolidates power and establishes lasting institutions.', 'https://images.pexels.com/photos/8134595/pexels-photo-8134595.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Kingdom_of_Rwanda', ARRAY['Nyiginya', 'Consolidation', 'Institutions']),
  ('ruganzu-ndori-reign', 'rwandan-kingdoms', 'Ruganzu II Ndori''s Expansion', 'c. 1510–1543 CE', 1510, 'King Ruganzu II Ndori, known as ''Ruganzu the Great,'' led successful military campaigns that significantly expanded Rwanda''s territory and established many of the kingdom''s lasting political and social institutions.', 'Ruganzu II Ndori expands the kingdom and strengthens royal power.', 'https://images.pexels.com/photos/8728382/pexels-photo-8728382.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Ruganzu_II_Ndoli', ARRAY['Ruganzu II Ndori', 'Expansion', 'Military']),
  ('mutara-semugeshi', 'rwandan-kingdoms', 'Mutara I Semugeshi''s Reforms', 'c. 1600–1624 CE', 1600, 'Mutara I Semugeshi introduced significant administrative reforms, including the ubuhake system of cattle clientship and the organization of the kingdom into provinces with appointed governors.', 'King Mutara I implements administrative and social reforms.', 'https://images.pexels.com/photos/2467285/pexels-photo-2467285.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Kingdom_of_Rwanda', ARRAY['Mutara I', 'Reforms', 'Administration']),
  ('yuhi-gahima', 'rwandan-kingdoms', 'Yuhi II Gahima''s Cultural Renaissance', 'c. 1648–1672 CE', 1648, 'King Yuhi II Gahima''s reign marked a cultural renaissance with the development of royal poetry, dance, and ceremonies. The famous Intore dancers and royal drummers reached new heights of artistic expression.', 'A period of cultural flourishing under King Yuhi II Gahima.', 'https://images.pexels.com/photos/12935073/pexels-photo-12935073.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Kingdom_of_Rwanda', ARRAY['Yuhi II Gahima', 'Culture', 'Arts']),
  ('mazimpaka-expansion', 'rwandan-kingdoms', 'Mazimpaka''s Territorial Peak', '1746–1802 CE', 1746, 'Under King Mazimpaka, Rwanda reached its largest territorial extent through successful military campaigns. He also refined the royal court ceremonies and strengthened the kingdom''s administrative structure.', 'King Mazimpaka expands Rwanda to its greatest territorial extent.', 'https://images.pexels.com/photos/1166209/pexels-photo-1166209.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Mazimpaka', ARRAY['Mazimpaka', 'Territorial Peak', 'Administration']),
  ('rwabugiri-modernization', 'rwandan-kingdoms', 'Rwabugiri''s Modernization Efforts', '1853–1895 CE', 1853, 'Kigeli IV Rwabugiri was the last independent king of Rwanda. He modernized the military, established diplomatic relations with European explorers, and maintained Rwanda''s independence through strategic alliances and military strength.', 'King Kigeli IV Rwabugiri modernizes the kingdom while maintaining independence.', 'https://images.pexels.com/photos/262780/pexels-photo-262780.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Kigeli_IV_Rwabugiri', ARRAY['Rwabugiri', 'Modernization', 'Independence']),
  ('colonial-encounter', 'rwandan-kingdoms', 'First Colonial Encounters', '1897–1900 CE', 1897, 'Following Rwabugiri''s death, Rwanda faced increasing pressure from German colonial forces. The kingdom''s traditional structures began to be challenged by European administrative systems and Christian missionary activities.', 'European colonial powers begin to establish control over Rwanda.', 'https://images.pexels.com/photos/63324/pexels-photo-63324.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/German_East_Africa', ARRAY['Colonial Period', 'German Rule', 'Traditional Authority']),
  ('monarchy-end', 'rwandan-kingdoms', 'End of the Monarchy', '1961 CE', 1961, 'The Rwandan Revolution of 1959-1961 led to the abolition of the monarchy and the establishment of a republic. King Kigeli V was forced into exile, ending over 500 years of continuous royal rule in Rwanda.', 'The Rwandan monarchy is abolished, ending centuries of royal rule.', 'https://images.pexels.com/photos/12935211/pexels-photo-12935211.jpeg?auto=compress&cs=tinysrgb&w=800', 'https://en.wikipedia.org/wiki/Rwandan_Revolution', ARRAY['Revolution', 'Republic', 'End of Monarchy'])
ON CONFLICT (id) DO NOTHING;